### ISSUE TITLE
Rubocop b0rk on web-ui

### ISSUE THREAD

**Issue by DanielJonesEB** [cloudfoundry/developer-training-class-apps#2]
I'm getting the following on my first CI build:

```
More information: https://github.com/rubocop-hq/rubocop-rails
Successfully installed rubocop-0.71.0
8 gems installed
Error: invalid EnforcedStyle 'when_needed' for Style/FrozenStringLiteralComment found in .rubocop.yml
Valid choices are: always, never
```

I haven't used RuboCop in years, and a cursory Google didn't suggest anything obvious. Should I do as the officer says and set it to either `always` or `never`?

Ping @spgreenberg

**Comment by spgreenberg** [comment]
Looks like they changed the valid options. I updated .rubocop.yml value to 'always'
